[package]
name = "bytecheck"
version = "0.6.5"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Derive macro for bytecheck"
license = "MIT"
documentation = "https://docs.rs/bytecheck"
repository = "https://github.com/djkoloski/bytecheck"
keywords = ["bytecheck", "validation", "zero-copy", "rkyv"]
categories = ["encoding"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck_derive = { version = "=0.6.5", path = "../bytecheck_derive", default-features = false }
ptr_meta = "0.1"
simdutf8 = { version = "0.1", default-features = false, optional = true }

# Support for various common crates. These are primarily to get users off the ground and build some
# momentum.

# These are NOT PLANNED to remain in bytecheck for the final release. Much like serde, these
# implementations should be moved into their respective crates over time. Before adding support for
# another crate, please consider getting bytecheck support in the crate instead.

uuid = { version = "0.8", optional = true }

[features]
default = []
verbose = []
simdutf8_std = ["simdutf8/std"]
std = ["bytecheck_derive/std"]
